using System;
using NewBuddah.PredictionV2.Bootstrap;
using UnityEngine;

namespace NewBuddah.PredictionV2.Debugging
{
    [Serializable]
    public class BuddahPredictionDebugState
    {
        public BuddahMovementRuntimeMode currentMode = BuddahMovementRuntimeMode.Legacy;
        public bool predictionActive;
        public bool legacyMovementEnabled = true;
        public bool predictedMotorEnabled;
        public bool isOwner;
        public bool movementAllowed = true;
        public bool gateBlocked;
        public bool ownerInputLive;
        public bool rigidbodyIsKinematic;
        public bool inputBridgeEnabled;
        public bool rooted;
        public bool invertTurnActive;
        public bool pushGraceActive;
        public bool suppressSteeringActive;
        public bool roomBypassActive;
        public bool lastImpulseConsumed;
        public bool reconcileHadCorrection;
        public bool lastTeleportConsumed;
        public bool modifiersClearedByTeleport;
        public bool impulseQueueClearedByTeleport;
        public bool pushGraceClearedByTeleport;
        public bool progressSnappedByTeleport;
        public bool trailRebasedByTeleport;
        public bool introControlActive;
        public bool externalKinematicControlActive;
        public bool handoffActive;
        public bool handoffSuppressSteeringActive;
        public bool handoffRoomBypassActive;
        public bool presentationControlActive;
        public bool ownerVisualRootStabilizationApplied;
        public bool ownerVisualRootStabilizationEnabled = true;
        public float steeringInput;
        public float planarSpeed;
        public float finalForwardForce;
        public float finalMaxSpeed;
        public float finalTurnTorque;
        public float finalSteeringSign = 1f;
        public float scaleMultiplier = 1f;
        public float preImpulseSpeed;
        public float postImpulseSpeed;
        public float lastImpulseTurnTorque;
        public float lastReconcilePositionDelta;
        public float lastReconcileVelocityDelta;
        public float lastReconcileVelocityPlanarDelta;
        public float lastReconcileVelocityVerticalDelta;
        public float preTeleportSpeed;
        public float postTeleportSpeed;
        public float preTeleportAngularSpeed;
        public float postTeleportAngularSpeed;
        public float lastTeleportTargetProgress01;
        public float lastTeleportTargetYaw;
        public float handoffSnapshotYaw;
        public float handoffSnapshotSpeed;
        public float handoffSnapshotAngularSpeed;
        public float preHandoffSpeed;
        public float postHandoffSpeed;
        public float motorVisualPosDelta;
        public float motorVisualYawDelta;
        public uint currentTick;
        public uint lastReplicateTick;
        public uint lastReconcileTick;
        public uint lastImpulseEventId;
        public uint lastImpulseEventTick;
        public uint lastTeleportEventId;
        public uint lastTeleportEventTick;
        public uint lastHandoffEventId;
        public uint lastHandoffEventTick;
        public uint handoffStartTick;
        public uint handoffLockedUntilTick;
        public uint rootUntilTick;
        public uint accelUntilTick;
        public uint postRootAccelUntilTick;
        public uint scaleUntilTick;
        public uint invertTurnUntilTick;
        public uint pushGraceUntilTick;
        public uint suppressSteeringUntilTick;
        public uint roomBypassUntilTick;
        public int pendingImpulseCount;
        public Vector3 lastImpulseVector;
        public Vector3 preTeleportPosition;
        public Vector3 postTeleportPosition;
        public Vector3 lastTeleportTargetPosition;
        public Vector3 handoffSnapshotPosition;
        public string predictionBlockReason = "n/a";
        public string activeModifiers = "none";
        public string lastImpulseSourceType = "none";
        public string lastTeleportSourceType = "none";
        public string launchState = "Normal";
        public string movementRootName = "null";
        public string visualRootName = "null";
        public string cameraFollowTargetName = "null";
        public string cameraDefaultFollowTargetName = "null";
        public string cameraReportedFollowTargetName = "null";
        public string cameraFollowDebugSource = "none";
        public bool cameraForceDefaultFollowTarget;
        public string cameraMode = "Normal";
        public string visualScaleSource = "default";
        public string externalControlSource = "none";
        public string ownerVisualRootStabilizationReason = "n/a";
        public string primaryTrack = "Legacy";
        public bool primaryTrackComplete;
        public bool fallbackActive;
        public int compatibilityLayerCount;
        public string systemMapSummary = "n/a";
        public string compatibilitySummary = "n/a";
        public string fallbackSummary = "n/a";
        public string highRiskFlagsSummary = "n/a";
        public string runtimeAutoAddSummary = "n/a";
        public string legacyResponsibilitySummary = "n/a";
        public string validationChecklistSummary = "n/a";
        public string movementChecklistSummary = "n/a";
        public string combatChecklistSummary = "n/a";
        public string presentationChecklistSummary = "n/a";
        public string legacyChecklistSummary = "n/a";
        public string healthSummary = "n/a";
        public string pendingImpulseSummary = "none";
        public string replicateSummary = "n/a";
        public string reconcileSummary = "n/a";
        public string lastLifecycleMessage = "Bootstrap pending";
    }
}
