using BuddahGo.AI;
using BuddahGo.Match;
using NUnit.Framework;
using UnityEngine;

public class AIDifficultyProfilesTests
{
    [TestCase(SoloDifficulty.Easy)] [TestCase(SoloDifficulty.Normal)] [TestCase(SoloDifficulty.Hard)]
    public void EveryTierLoadsAValidThrustVectorProfile(SoloDifficulty tier)
    {
        var profile = AIDifficultyProfiles.Load(tier);
        Assert.That(profile, Is.Not.Null, "Resources/AI/" + tier + ".asset is generated by AIDifficultyAssetTool.Build");
        Assert.That(profile.UseWallCorridor, Is.True);
        Assert.DoesNotThrow(profile.ValidateConfiguration);
    }

    [Test] public void TiersAreOrderedByBoldnessAndReaction()
    {
        var easy = AIDifficultyProfiles.Load(SoloDifficulty.Easy); var normal = AIDifficultyProfiles.Load(SoloDifficulty.Normal); var hard = AIDifficultyProfiles.Load(SoloDifficulty.Hard);
        Assert.That(easy.TargetSpeed, Is.LessThanOrEqualTo(normal.TargetSpeed)); Assert.That(normal.TargetSpeed, Is.LessThanOrEqualTo(hard.TargetSpeed));
        Assert.That(easy.ReactionTicks, Is.GreaterThanOrEqualTo(normal.ReactionTicks)); Assert.That(normal.ReactionTicks, Is.GreaterThanOrEqualTo(hard.ReactionTicks));
        Assert.That(easy.RolloutWallWeight, Is.GreaterThanOrEqualTo(normal.RolloutWallWeight)); Assert.That(normal.RolloutWallWeight, Is.GreaterThanOrEqualTo(hard.RolloutWallWeight));
        Assert.That(hard.MaxThrustAngleDegrees, Is.LessThanOrEqualTo(normal.MaxThrustAngleDegrees), "Hard never brakes (thrust angle <= 90)");
    }

    [Test] public void ResolveGivesEachRacerItsOwnInstanceWithLineVariety()
    {
        var a = AIDifficultyProfiles.Resolve(SoloDifficulty.Normal, 0); var b = AIDifficultyProfiles.Resolve(SoloDifficulty.Normal, 1);
        try
        {
            Assert.That(a, Is.Not.SameAs(b)); Assert.That(a, Is.Not.SameAs(AIDifficultyProfiles.Load(SoloDifficulty.Normal)));
            Assert.That(a.LateralOffset, Is.Not.EqualTo(b.LateralOffset));
        }
        finally { Object.DestroyImmediate(a); Object.DestroyImmediate(b); }
    }

    [Test]
    public void ProfileRejectsNonFiniteAndOutOfRangeValues()
    {
        var profile = ScriptableObject.CreateInstance<AIDifficultyProfile>();
        try
        {
            profile.ValidateConfiguration();
            profile.TargetSpeed = float.NaN;
            Assert.Throws<System.ArgumentException>(() => profile.ValidateConfiguration());
            profile.TargetSpeed = 80f; profile.RolloutSampleTicks = 0;
            Assert.Throws<System.ArgumentException>(() => profile.ValidateConfiguration());
        }
        finally { Object.DestroyImmediate(profile); }
    }
}
